services:
    status.manager:
        class: StatusBundle\Entity\Status
        arguments: []
#    status.example:
#        class: StatusBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
